bussines/apps/business/urls.py
from django.contrib import admin
from apps.business.views import index_business, BusinessList, BusinessCreate, BusinessUpdate, BusinessDelete
from django.urls import path, re_path, include

urlpatterns = [
    path('', index_business, name='inicio'),
    path('business/listar', BusinessList.as_view(), name='business_listar'),
    path('business/nueva', BusinessCreate.as_view(), name='business_crear'),
    path('business/editar/<pk>/', BusinessUpdate.as_view(), name='business_editar'),
    path('business/eliminar/<pk>/', BusinessDelete.as_view(), name='business_eliminar'),
]

bussines/apps/oportunidad/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from apps.oportunidad.views import listadousuarios, index, oportunidad_view, oportunidad_list, oportunidad_edit, oportunidad_delete, OportunidadList, OportunidadCreate, OportunidadUpdate, OportunidadDelete
from django.urls import path, re_path, include
app_name = 'oportunidad'
urlpatterns = [
    path('',index,name='index'),
    path('nuevo/',login_required(OportunidadCreate.as_view()),name='oportunidad_crear'),
    path('listar/',login_required(OportunidadList.as_view()),name='oportunidad_listar'),
    path('editar/<pk>/',login_required(OportunidadUpdate.as_view()),name='oportunidad_editar'),
    path('eliminar/<pk>/',login_required(OportunidadDelete.as_view()),name='oportunidad_eliminar'),
    path('listado/', listadousuarios,name='listado'),
]

bussines/apps/usuario/urls.py
from django.urls import path, re_path, include
from apps.usuario.views import RegistroUsuario, UserAPI

urlpatterns = [
    path('registrar/', RegistroUsuario.as_view(), name='registrar'),   
    path('api/', UserAPI.as_view(), name="api"),
]

bussines/bussines/urls.py
from django.contrib import admin
from django.urls import include, path, re_path as path
from django.contrib.auth.views import logout_then_login, LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


urlpatterns = [
    path('admin/', admin.site.urls),
    path('oportunidad/',include(('apps.oportunidad.urls','oportunidad'), namespace='oportunidad')),
    path('business/',include(('apps.business.urls','business'), namespace='business')),
    path('usuario/',include(('apps.usuario.urls','usuario'), namespace='usuario')),
    path('accounts/login/', LoginView.as_view(template_name='index.html',success_url=reverse_lazy('oportunidad_listar')), name='login'),
    path('logout/', logout_then_login, name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         {'email_template_name':'registration/password_reset_email.html'}, name="password_reset"),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name="password_reset_confirm"),
    path('reset/done', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name="password_reset_complete"),
]

bussines/apps/business/models.py
from django.db import models

# Create your models here.
class Persona(models.Model):
    creador = models.CharField(max_length = 100)
    nit = models.CharField(max_length = 100)
    nombre_empresa = models.CharField(max_length = 100)
    nombre_comercial = models.CharField(max_length = 100)
    direccion = models.CharField(max_length = 100)
    telefono = models.CharField(max_length = 100)
    correo = models.EmailField()
    sitio_web = models.URLField(max_length = 100)
    pais = models.CharField(max_length = 100)
    estado = models.CharField(max_length = 100)
    ciudad = models.CharField(max_length = 100)
    usuarios_empresa = models.IntegerField()

    def __str__(self):
        return '{} {}'.format(self.creador, self.correo)

class Business(models.Model):
    numero_oportunidad = models.IntegerField()
    contactos = models.IntegerField()

bussines/apps/oportunidad/models.py
from django.db import models
from apps.business.models import Persona

# Create your models here.

class Oportunidad(models.Model):
    TITULOS_ESTADOS =[
        ('En proceso', 'En proceso'),
        ('Ganada', 'Ganada'),
        ('No ganada', 'No ganada'),
        ('Cancelada(Descartada)', 'Cancelada(Descartada)'),
    ]
    #identificador = models.UUIDField()
    empresa_cliente = models.CharField(max_length = 500)
    contacto_empresa = models.CharField(max_length = 50)
    nombre_oportunidad = models.CharField(max_length = 50)
    monto_oportunidad = models.IntegerField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    estado = models.CharField(max_length = 50, choices=TITULOS_ESTADOS)

bussines/apps/usuario/models.py
from django.db import models

# Create your models here.

bussines/apps/business/forms.py
from django import forms

from apps.business.models import Persona, Business

class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = [
            'creador',
            'nit',
            'nombre_empresa',
            'nombre_comercial',
            'direccion',
            'telefono',
            'correo',
            'sitio_web',
            'pais',
            'estado',
            'ciudad',
            'usuarios_empresa',
        ]
        labels = {
            'creador': "Usuario creador",
            'nit': "Nit",
            'nombre_empresa': "Nombre de la empresa",
            'nombre_comercial': 'Nombre comercial de la empresa',
            'direccion': "Dirección",
            'telefono': 'Telefono',
            'correo': 'Correo electrónico',
            'sitio_web': 'Sitio web',
            'pais': 'País',
            'estado': 'Departamento',
            'ciudad':'Ciudad',
            'usuarios_empresa': 'Usuarios de la empresa',

        }
        widgets = {
            'creador': forms.TextInput(attrs={'class':'form-control'}),
            'nit': forms.TextInput(attrs={'class':'form-control'}),
            'nombre_empresa': forms.TextInput(attrs={'class':'form-control'}),
            'nombre_comercial': forms.TextInput(attrs={'class':'form-control'}),
            'direccion': forms.TextInput(attrs={'class':'form-control'}),
            'telefono': forms.TextInput(attrs={'class':'form-control'}),
            'correo': forms.EmailInput(attrs={'class':'form-control'}),
            'sitio_web': forms.URLInput(attrs={'class':'form-control'}),
            'pais': forms.TextInput(attrs={'class':'form-control'}),
            'estado': forms.TextInput(attrs={'class':'form-control'}),
            'ciudad': forms.TextInput(attrs={'class':'form-control'}),
            'usuarios_empresa': forms.TextInput(attrs={'class':'form-control'}),
        }

class BusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = [
            'numero_oportunidad', 
            'contactos'
        ]
        labels = {
            'numero_oportunidad': 'Correo electrónico', 
            'contactos': 'Contactos de la empresa'
        }
        widgets = {
            'numero_oportunidad': forms.TextInput(attrs={'class':'form-control'}),
            'contactos': forms.Textarea(attrs={'class':'form-control'}),
        }

bussines/apps/oportunidad/forms.py
from django import forms

from apps.oportunidad.models import Oportunidad


class OportunidadForm(forms.ModelForm):

	class Meta:
		model = Oportunidad

		fields = [
			#'identificador',
			'empresa_cliente',
			'contacto_empresa',
			'nombre_oportunidad',
			'monto_oportunidad',
			'persona',
			'estado',
		]
		labels = {
			#'identificador': 'Identificador',
			'empresa_cliente': 'Empresa cliente',
			'contacto_empresa': 'Contacto de la empresa',
			'nombre_oportunidad': 'Nombre oportunidad',
			'monto_oportunidad': 'Monto oportunidad',
			'persona': 'Persona',
			'estado': 'Estado',
		}
		widgets = {
			#'identificador': forms.TextInput(attrs={'class':'form-control'}),
			'empresa_cliente': forms.TextInput(attrs={'class':'form-control'}),
			'contacto_empresa': forms.TextInput(attrs={'class':'form-control'}),
			'nombre_oportunidad': forms.TextInput(attrs={'class':'form-control'}),
			'monto_oportunidad': forms.TextInput(attrs={'class':'form-control'}),
			'persona': forms.Select(attrs={'class':'form-control'}),
			'estado': forms.Select(attrs={'class':'form-control'}),
		}

bussines/apps/usuario/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistroForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email'
        ]
        labels = {
            'username': 'Username',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'email': 'Correo electrónico'
        }

bussines/apps/business/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from apps.business.models import Persona, Business
from django.contrib.auth.models import User
# Create your views here.
from apps.business.forms import PersonaForm, BusinessForm
from django.urls import reverse_lazy

def index_business(request):
    return HttpResponse("Soy la página business")

class BusinessList(ListView):
    model = Business
    template_name = 'business/business_list.html'

class BusinessCreate(CreateView):
    model = Business
    template_name = 'business/business_form.html'
    form_class = BusinessForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('business:business_listar')

    def get_context_data(self, **kwargs):
        context = super(BusinessCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
        return context
    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            business = form.save(commit=False)
            business.persona = form2.save()
            business.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2=form2))


class BusinessUpdate(UpdateView):
    model = Business
    second_model = Persona
    template_name = 'business/business_form.html'
    form_class = BusinessForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('business:business_listar')

    def get_context_data(self, **kwargs):
        context = super(BusinessUpdate, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        business = self.model.objects.get(id=pk)
        persona = self.second_model.objects.get(id=business.persona_id)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=persona)
        context['id'] = pk
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_business = kwargs['pk']
        business = self.model.objects.get(id=id_business)
        persona = self.second_model.objects.get(id=business.persona_id)
        form = self.form_class(request.POST, instance=business)
        form2 = self.second_form_class(request.POST, instance=persona)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())

class BusinessDelete(DeleteView):
    model = Business
    template_name = 'business/business_delete.html'
    success_url = reverse_lazy('business:business_listar')

bussines/apps/oportunidad/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from apps.oportunidad.forms import OportunidadForm
from django.core import serializers
from apps.oportunidad.models import Oportunidad
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
# Create your views here.

def listadousuarios(request):
	lista = serializers.serialize('json', User.objects.all(), fields=['username', 'first_name'])
	return HttpResponse(lista, content_type='application/json')

def index(request):
	return render(request, 'oportunidad/index.html')

def oportunidad_view(request):
	if request.method == 'POST':
		form = OportunidadForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('oportunidad:oportunidad_listar')
	else:
		form = OportunidadForm()
	return render(request, 'oportunidad/oportunidad_form.html', {'form':form})

def oportunidad_list(request):
	oportunidad = Oportunidad.objects.all()
	contexto = {'oportunidad':oportunidad, 'form':form}
	return render(request, 'oportunidad/oportunidad_list.html', contexto)

def oportunidad_edit(request, id_oportunidad):
	oportunidad = Oportunidad.objects.get(id=id_oportunidad)
	if request.method == 'GET':
		form = OportunidadForm(instance=oportunidad)
	else:
		form = OportunidadForm(request.POST, instance=oportunidad)
		if form.is_valid():
			form.save()
		return redirect('oportunidad:oportunidad_listar')
	return render(request, 'oportunidad/oportunidad_form.html', {'form':form})

def oportunidad_delete(request, id_oportunidad):
	oportunidad = Oportunidad.objects.get(id=id_oportunidad)
	if request.method == 'POST':
		oportunidad.delete()
		return redirect('oportunidad:oportunidad_listar')
	return render(request, 'oportunidad/oportunidad_delete.html', {'oportunidad':oportunidad})

class OportunidadList(ListView):
	model = Oportunidad
	template_name = 'oportunidad/oportunidad_list.html'
	paginate_by = 2

class OportunidadCreate(CreateView):
	model = Oportunidad
	form_class = OportunidadForm
	template_name = 'oportunidad/oportunidad_form.html'
	success_url = reverse_lazy('oportunidad:oportunidad_listar')

class OportunidadUpdate(UpdateView):
	model = Oportunidad
	form_class = OportunidadForm
	template_name = 'oportunidad/oportunidad_form.html'
	success_url = reverse_lazy('oportunidad:oportunidad_listar')

class OportunidadDelete(DeleteView):
	model = Oportunidad
	template_name = 'oportunidad/oportunidad_delete.html'
	success_url = reverse_lazy('oportunidad:oportunidad_listar')

bussines/apps/usuario/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from apps.usuario.forms import RegistroForm
from rest_framework.views import APIView
from apps.usuario.serializers import UserSerializer
import json
from django.http import HttpResponse
# Create your views here.

class RegistroUsuario(CreateView):
    model = User
    template_name = 'usuario/register.html'
    form_class = RegistroForm
    success_url = reverse_lazy('oportunidad:oportunidad_listar')

class UserAPI(APIView):
    serializer = UserSerializer

    def get(self, request, format=None):
        lista = User.objects.all()
        response = self.serializer(lista, many=True)
        return HttpResponse(json.dumps(response.data), content_type='application/json')

bussines/templates/business/business_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>¿Esta seguro de eliminar la business de {{ object.persona.nombre }} {{ object.persona.apellidos }}?</h3>
    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
    <a class="btn btn-default" href="{% url 'oportunidad:oportunidad_listar' %}">Cancelar</a>
</form>
{% endblock %}

bussines/templates/business/business_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form2.nombre.name}}">{{form2.creador.label}}</label>
            {{form2.creador}}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form2.nombre.name}}">{{form2.nit.label}}</label>
            {{form2.nit}}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form2.nombre.name}}">{{form2.nombre_empresa.label}}</label>
            {{form2.nombre_empresa}}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form2.nombre.name}}">{{form2.nombre_comercial.label}}</label>
            {{form2.nombre_comercial}}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form2.nombre.name}}">{{form2.direccion.label}}</label>
            {{form2.direccion}}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form2.nombre.name}}">{{form2.telefono.label}}</label>
            {{form2.telefono}}
            </div>
        </div>    
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form2.nombre.name}}">{{form2.correo.label}}</label>
            {{form2.correo}}
            </div>
        </div>    
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form2.nombre.name}}">{{form2.sitio_web.label}}</label>
            {{form2.sitio_web}}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form.pais.name}}">{{form2.pais.label}}</label>
            {{form2.pais}}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form2.estado.name}}">{{form2.estado.label}}</label>
            {{form2.estado}}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form2.ciudad.name}}">{{form2.ciudad.label}}</label>
            {{form2.ciudad}}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form2.ciudad.name}}">{{form2.usuarios_empresa.label}}</label>
            {{form2.usuarios_empresa}}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Guardar</button>
            </div>
        </div>    
    </div>
</form>
{% endblock %}

bussines/templates/business/business_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
    <thead>
        <tr>
            <td>Usuario creador</td>
            <td>Nit</td>
            <td>Nombre de la empresa</td>
            <td>Nombre comercial de la empresa</td>
            <td>Dirección</td>
            <td>Teléfono</td>
            <td>Correo electrónico</td>
            <td>Sitio web</td>
            <td>País</td>
            <td>Departamento</td>
            <td>Ciudad</td>
            <td>Usuarios que pertenecen a la empresa</td>
            <td>Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% if object_list %}
        {% for persona in object_list %}
        <tr>
            <td>{{ persona.creador }}</td>
            <td>{{ persona.nit }}</td>
            <td>{{ persona.nombre_empresa }}</td>
            <td>{{ persona.nombre_comercial }}</td>
            <td>{{ persona.direccion }}</td>
            <td>{{ persona.telefono }}</td>
            <td>{{ persona.correo }}</td>
            <td>{{ persona.sitio_web }}</td>
            <td>{{ persona.pais }}</td>
            <td>{{ persona.estado }}</td>
            <td>{{ persona.ciudad }}</td>
            <td>{{ persona.usuarios_empresa }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'business:business_editar' persona.id %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'business:business_eliminar' persona.id %}">Eliminar</a>
            </td>
        </tr>
        {% endfor %}

        {% else %}
        <h1>No hay registros de business</h1>
        {% endif %}
    </tbody>
</table>
{% endblock %}